CUDA_VISIBLE_DEVICES=0 th TorchTrainRankingHomogeniousDataset.lua \
-model_name ranking_model_8 \
-dataset_name 3DRobotTrainingSet \
-experiment_name QA_pretraining \
-datasets_dir /home/lupoglaz/ProteinsDataset/ \
-learning_rate 0.001 \
-learning_rate_decay 0.0 \
-l2_coef 0.001 \
-tm_score_threshold 0.1 \
-gap_weight 0.1 \
-validation_period 1 \
-model_save_period 10 \
-max_epoch 150 \
-decoys_ranking_mode gdt-ts \
-gpu_num 1 