CUDA_VISIBLE_DEVICES=0 th TorchTrainRankingHomogeniousDataset.lua \
-model_name ranking_model_8 \
-dataset_name AgregateDataset \
-experiment_name QAL2 \
-datasets_dir /home/lupoglaz/ProteinsDataset/ \
-learning_rate 0.0075 \
-learning_rate_decay 0.001 \
-l2_coef 0.00005 \
-tm_score_threshold 0.01 \
-gap_weight 0.1 \
-validation_period 1 \
-model_save_period 1 \
-max_epoch 100 \
-decoys_ranking_mode gdt-ts \
-gpu_num 1 \
-restart