th TorchTrainRankingHomogeniousDataset.lua \
-model_name ranking_model_8 \
-dataset_name CASP_SCWRL \
-models_dir /media/lupoglaz/3DCNN_MAQ_models/ \
-experiment_name QA4 \
-datasets_dir /home/lupoglaz/TMP_DATASETS/ \
-learning_rate 0.001 \
-learning_rate_decay 0.0001 \
-l2_coef 0.0 \
-tm_score_threshold 0.1 \
-gap_weight 0.1 \
-validation_period 1 \
-model_save_period 1 \
-max_epoch 150 \
-decoys_ranking_mode gdt-ts \
-gpu_num 1
