CUDA_VISIBLE_DEVICES=0 th TorchTrainRegression.lua \
-model_name ranking_model_8 \
-dataset_name CASP_SCWRL \
-experiment_name QA_regression \
-datasets_dir /home/lupoglaz/ProteinsDataset/ \
-learning_rate 0.0003 \
-learning_rate_decay 0.01 \
-l2_coef 0.0 \
-validation_period 5 \
-train_rescoring_period 20 \
-model_save_period 5 \
-max_epoch 150 \
-decoys_ranking_mode gdt-ts \
-gpu_num 1 \
-restart \
-restart_epoch 65