CUDA_VISIBLE_DEVICES=0 th TorchTrainRankingHomogeniousDataset.lua \
-model_name ranking_model_8 \
-dataset_name AgregateDataset \
-experiment_name QA \
-datasets_dir /home/lupoglaz/ProteinsDataset/ \
-learning_rate 0.0001 \
-l1_coef 0.00001 \
-tm_score_threshold 0.01 \
-gap_weight 0.1 \
-validation_period 10 \
-model_save_period 10 \
-max_epoch 150 \
-decoys_ranking_mode gdt-ts \
-gpu_num 1 \
-restart