CUDA_VISIBLE_DEVICES=0 th TorchTrainRefine.lua \
-model_name ranking_model_8 \
-dataset_name CASP_SCWRL \
-experiment_name QA_refine \
-datasets_dir /home/lupoglaz/ProteinsDataset/ \
-learning_rate 0.0003 \
-learning_rate_decay 0.01 \
-l2_coef 0.0 \
-tm_score_threshold 0.01 \
-gap_weight 0.1 \
-validation_period 1 \
-model_save_period 1 \
-max_epoch 150 \
-decoys_ranking_mode gdt-ts \
-gpu_num 1 \
-restart \
-restart_epoch 40 \
-restart_dir /home/lupoglaz/Projects/MILA/deep_folder/models/QA_uniform_ranking_model_8_CASP_SCWRL/